# Claude assisted rewrites lol - check claude chat history if it's still there
#
# To trigger and update directly on k3s to pull a fresh image: 'kubectl rollout restart deployment -n pihole'
# it might take a minute, be patient
#
# To check pods 'https://claude.ai/chat/ccafa328-89e4-4c61-8de5-86ae11cf3d75'
#
# moved to this list after pluto tv was exploding - https://github.com/hagezi/dns-blocklists
# https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
# 
apiVersion: v1
kind: Namespace
metadata:
  name: pihole  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1 # TODO, multi replica? 2-3?
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        kubernetes.io/os: linux
        hardware: rpi4
      containers:
      - name: pihole
        image: pihole/pihole:latest # https://hub.docker.com/r/pihole/pihole/tags
        imagePullPolicy: IfNotPresent
        env: # https://github.com/pi-hole/docker-pi-hole#upgrading-persistence-and-customizations
        - name: TZ
          value: "America/Los_Angeles"
        - name: WEBPASSWORD
          value: changethisdefaultpassword
        securityContext: # Do not allow to run in privileged mode, probably doesn't matter but allowing privileged is asking for me to get pwned if I get pwned.
          capabilities:
            add: ["NET_ADMIN", "NET_BIND_SERVICE"]
          privileged: false
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 67
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        volumeMounts: # copy pasta same as below
        - name: pihole-config
          mountPath: /etc/pihole
        - name: dnsmasq-config  # Add this mount
          mountPath: /etc/dnsmasq.d
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits: # It hasn't been an issue so far, but from practice at work, limits seem more trouble than they are worth.
            memory: 2Gi
            cpu: 1000m
      volumes:
      - name: pihole-config
        hostPath:
          path: /etc/pihole/
          type: Directory
        #persistentVolumeClaim:
        #  claimName: longhorn-pihole-data
      - name: dnsmasq-config
        hostPath:
          path: /etc/dnsmasq.d
          type: Directory
        #persistentVolumeClaim:
        #  claimName: longhorn-pihole-dnsmasq
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-web-service
  namespace : pihole
spec:
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name : web
  type: LoadBalancer 
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-service
  namespace: pihole
spec:
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name : dns
  type: LoadBalancer 
#--- # https://docs.k3s.io/storage
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: longhorn-pihole-data
#  namespace: pihole
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: longhorn
#  resources:
#    requests:
#      storage: 500Mi
#--- # https://docs.k3s.io/storage
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: longhorn-pihole-dnsmasq
#  namespace: pihole
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: longhorn
#  resources:
#    requests:
#      storage: 500Mi
