apiVersion: v1
kind: Pod
metadata:
  name: pihole
  namespace: pihole
spec:
  hostNetwork: true
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      # upstream DNS used by pihole.
      - 9.9.9.9
  containers:
    - name: pihole
      # https://hub.docker.com/r/pihole/pihole/tags
      image: pihole/pihole:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: WEBPASSWORD
          value: changethisdefaultpassword
      securityContext:
        privileged: true
      ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 67
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
      volumeMounts:
        - name: etc
          mountPath: /etc/pihole
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 2Gi
          cpu: 1
  volumes:
    - name: etc
      hostPath:
        path: /data/pihole/etc
        type: Directory
    - name: dnsmasq
      hostPath:
        path: /data/pihole/dnsmasq.d
        type: Directory