# https://jellyfin.org/docs/general/installation/container
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - type: bind
        source: /path/to/media
        target: /media
      - type: bind
        source: /path/to/media2
        target: /media2
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: /path/to/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

# 1. Install Jellyfin on your system with the installation method for your platform.^^
#
# 2. Edit the web configuration and adjust the options to fit your desired privacy level.
#    https://jellyfin.org/docs/general/clients/web-config
#
# 3. Our defaults sacrifice some absolute self-hosting for often requested features.
#    If this is concerning, please review the documentation and edit accordingly.
#    Browse to http://SERVER_IP:8096 to access the included web client.
#
# 4. Follow the initial setup wizard.
#
# 5. Libraries and users can always be added later from the dashboard.
# Remember the username and password so you can login after the setup.
# Secure the server with a method of your choice.
#
# 6. Create an SSL certificate and add it on the Networking page.
# Put your server behind a reverse proxy. 
# (https://jellyfin.org/docs/general/networking/#running-jellyfin-behind-a-reverse-proxy)
# Only allow local connections and refrain from forwarding any ports.
# Enjoy your media!
