# actual docs - https://docs.pi-hole.net/main/origins/
# my original reference - https://uthark.github.io/post/2021-10-06-running-pihole-kubernetes/
# this didn't really work for me because it needs persistent volume storage.. and tbh i don't need that. lol. it's two files.
# modified this to make the below - https://www.virtualthoughts.co.uk/2019/10/23/k8s-metallb-and-pihole/
#
# To trigger and update directly on k3s to pull a fresh image: 'kubectl rollout restart deployment -n pihole'
# it might take a minute, be patient
# 
#
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-adlists
  namespace: pihole
data: # moved to this list after pluto tv was exploding
  adlists.list: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-regex
  namespace: pihole
data:
  regex.list: |
    ^(.+[-_.])??adse?rv(er?|ice)?s?[0-9]*[-.]
    ^(.+[-_.])??m?ad[sxv]?[0-9]*[-_.]
    ^(.+[-_.])??telemetry[-.]
    ^(.+[-_.])??xn--
    ^adim(age|g)s?[0-9]*[-_.]
    ^adtrack(er|ing)?[0-9]*[-.]
    ^advert(s|is(ing|ements?))?[0-9]*[-_.]
    ^aff(iliat(es?|ion))?[-.]
    ^analytics?[-.]
    ^banners?[-.]
    ^beacons?[0-9]*[-.]
    ^count(ers?)?[0-9]*[-.]
    ^pixels?[-.]
    ^stat(s|istics)?[0-9]*[-.]
    ^track(ers?|ing)?[0-9]*[-.]
    ^traff(ic)?[-.]
    ^(.*)\.g00\.(.*)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1 # would be cool to multi replica this but i don't think pihole directly supports this?
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          # upstream DNS used by pihole.
          - 9.9.9.9
          - 1.1.1.1 # maybe i can use cloudflare as backup? let's see what happens, can't be worse than before
      containers:
      - name: pihole
        # https://hub.docker.com/r/pihole/pihole/tags
        image: pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: WEBPASSWORD
          value: changethisdefaultpassword
        securityContext:
          privileged: true
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 67
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: pihole-adlists
          mountPath: /etc/pihole/adlists.list
          subPath: adlists.list
        - name: pihole-regex
          mountPath: /etc/pihole/regex.list
          subPath: regex.list
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
      volumes:
        - name: pihole-adlists
          configMap:
            name: pihole-adlists
        - name: pihole-regex
          configMap: 
            name: pihole-regex
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-web-service
  namespace : pihole
spec:
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name : web
  type: LoadBalancer 
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-service
  namespace: pihole
spec:
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name : dns
  type: LoadBalancer 
